services:
  spotify_backend_sever:
    image: spotify_server
    ports:
      - 5000:6000
      - 6002:6002
      - 8080:8080
  
    volumes:
      - ./backend/Spotify.Infrastructure/spotify.db:/app/Spotify.Infrastructure/spotify.db
      - ./backend/Spotify.Infrastructure/Persistence/Uploads:/app/Spotify.Infrastructure/Persistence/Uploads